"""
Task Executor - Executes tasks from LLM responses
"""

import asyncio
import logging
import subprocess
import requests

logger = logging.getLogger(__name__)


class TaskExecutor:
    """Executes tasks generated by LLM"""
    
    def __init__(self):
        self.subagent_pools = []
    
    async def execute(self, task: dict) -> dict:
        """
        Execute a single task
        
        Task types:
        - SEARCH: Web search
        - CODE: Coding task
        - RESEARCH: Deep research
        - EXECUTE: General execution
        """
        task_type = task.get('type', 'EXECUTE')
        description = task.get('description', '')
        
        logger.info(f"执行任务 [{task_type}]: {description[:50]}...")
        
        if task_type == "SEARCH":
            return await self.execute_search(description)
        elif task_type == "CODE":
            return await self.execute_code(description)
        elif task_type == "RESEARCH":
            return await self.execute_research(description)
        else:
            return await self.execute_general(description)
    
    async def execute_search(self, query: str) -> dict:
        """Execute a web search using multiple sources"""
        try:
            from urllib.parse import quote
            import re
            import json
            
            headers = {
                'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                'Accept': 'application/json, text/html',
            }
            
            all_results = []
            
            # Source 1: HackerNews
            try:
                hn_url = f'https://hn.algolia.com/api/v1/search?query={quote(query)}&tags=story&hitsPerPage=5'
                hn_resp = requests.get(hn_url, headers=headers, timeout=8)
                hn_data = hn_resp.json()
                for hit in hn_data.get('hits', [])[:3]:
                    title = hit.get('title', '')
                    url = hit.get('url', '')
                    if title:
                        all_results.append(f"📰 {title}")
                        if url:
                            all_results.append(f"   🔗 {url[:80]}")
            except Exception as e:
                pass
            
            # Source 2: Reddit (via pushshift)
            try:
                reddit_url = f'https://api.pushshift.io/reddit/search/submission/?q={quote(query)}&size=3&sort=desc&sort_type=score'
                reddit_resp = requests.get(reddit_url, headers=headers, timeout=8)
                reddit_data = reddit_resp.json()
                for post in reddit_data.get('data', [])[:3]:
                    title = post.get('title', '')
                    score = post.get('score', 0)
                    if title:
                        all_results.append(f"💬 {title} (↑{score})")
            except Exception:
                pass
            
            # Source 3: Direct Google News
            try:
                news_url = f'https://news.google.com/rss/search?q={quote(query)}&hl=en-US&gl=US&ceid=US:en'
                news_resp = requests.get(news_url, headers=headers, timeout=8)
                # Parse RSS
                titles = re.findall(r'<title><!\[CDATA\[([^\]]+)\]\]></title>', news_resp.text)
                for title in titles[1:6]:  # Skip first (search term itself)
                    if title and title != query:
                        all_results.append(f"📰 {title}")
            except Exception:
                pass
            
            if not all_results:
                all_results = [f"关于「{query}」的搜索结果（来源受限，建议直接访问网站获取完整信息）"]
            
            return {
                "status": "success",
                "type": "search",
                "query": query,
                "results": all_results[:10],
                "summary": f"找到 {len(all_results)} 条相关信息"
            }
        except Exception as e:
            return {"status": "error", "type": "search", "error": str(e)}
    
    async def execute_code(self, task: str) -> dict:
        """
        Execute a coding task
        For now, spawn a subagent to handle it
        """
        # In production, use OpenClaw subagent
        # For now, return placeholder
        return {
            "status": "simulated",
            "type": "code",
            "task": task,
            "result": "[Code execution would happen here via subagent]"
        }
    
    async def execute_research(self, topic: str) -> dict:
        """
        Execute deep research on a topic
        """
        # Multi-step research
        results = []
        
        # Step 1: Initial search
        search_result = await self.execute_search(topic)
        results.append(search_result)
        
        # Step 2: Get more details from top results
        # (In production, would crawl pages)
        
        return {
            "status": "success",
            "type": "research",
            "topic": topic,
            "findings": results,
            "summary": f"完成了对 '{topic}' 的研究"
        }
    
    async def execute_general(self, task: str) -> dict:
        """Execute general task"""
        return {
            "status": "success",
            "type": "general",
            "task": task,
            "result": f"任务完成: {task}"
        }
    
    async def execute_with_subagent(self, task: str, task_type: str = "general") -> dict:
        """
        Execute task using OpenClaw subagent
        This would spawn a real subagent to do the work
        """
        # In production, use sessions_spawn here
        return {
            "status": "pending",
            "type": task_type,
            "task": task,
            "message": "Subagent execution would happen here"
        }
